### ISSUE TITLE
logged in users only

### ISSUE THREAD

**Issue by teatall** [murfman-de/slim-wiki#13]
Is there a way to allow only logged in users to read the wiki?

**Comment by til-schneider** [comment]
No. But I'd suggest to use Base-Authentication configured in your webserver instead for this purpose.

**Comment by teatall** [comment]
> No. But I'd suggest to use Base-Authentication configured in your webserver instead for this purpose.

thanks

**Comment by teatall** [comment]
> No. But I'd suggest to use Base-Authentication configured in your webserver instead for this purpose.

thanks
