### ISSUE TITLE
Error "Not logged in" when saving

### ISSUE THREAD

**Issue by fragmentbyte** [murfman-de/slim-wiki#4]
`Calling RPC editor.saveArticle failed: Not logged in`

How to fix it?

---
- If I log into the browser's incognito mode, everything works.
- If you comment out line 92 of EditorService.php (`$this->assertLoggedIn();`), all works. What makes this line?

**Comment by til-schneider** [comment]
The line `$this->assertLoggedIn();` checks whether the user is logged in. If you remove it, everyone can edit your wiki.

Which version are you using? This should already be fixed in the development version (see 92195f431ac4be64f8855e7170fce680222cdabe). But it isn't fixed in version 1.

**Comment by fragmentbyte** [comment]
Yes, I use version 1. I try to carefully update files. Thank you!

**Comment by fragmentbyte** [comment]
And I have all broken. Please put the latest build. I can't build.

**Comment by til-schneider** [comment]
I've just created version 2.
Please note: You have to move the directory `articles` into `data`.

**Comment by fragmentbyte** [comment]
```
[14-Mar-2016 14:49:13 Europe/Berlin] PHP Warning:  file_put_contents(/home/zuomekkx/test/data/articles/docs/start): failed to open stream: Is a directory in /home/zuomekkx/test/server/logic/EditorService.php on line 107
```

when saving

**Comment by til-schneider** [comment]
You have to put a `/` at the end of your link. E.g.: `[My page](docs/start/)`

**Comment by fragmentbyte** [comment]
Yes, but links in Breadcrumbs do not `/` at the end ( `home/docs/start` )

**Comment by til-schneider** [comment]
Grmpf. You're right. I've fixed this in efa639d6cfd6ae50fabc41f07944a44f025073c6. Links to directories are now working with or without a trailing `/`.

Just exchange the `Main.php` using the newest version. I've updated version 2, too.

**Comment by fragmentbyte** [comment]
Thank you so much! It seems that now everything is perfect)

**Comment by passazhir** [comment]
Thank you so much! It seems that now everything is perfect)
