### ISSUE TITLE
Add TOC

### ISSUE THREAD

**Issue by fragmentbyte** [murfman-de/slim-wiki#6]
It would be useful to add the ability to create a table of contents. I tried using Markdown:

```
[itemtoc](#T1)

## Title {#T1}
```

But `\page#T1` recognized as a new page.

**Comment by til-schneider** [comment]
Yes, a TOC is planned. But I thought of a TOC which is generated automatically if your article contains more than x headlines (where x is configurable). This TOC would be shown floating on the right side.

But you're right. Links with a hash are treated wrong. This is a bug.

In your example, you use `{#T1}` for creating the anchor. I don't know this syntax. Is this any kind of Markdown? Where did you find this?

**Comment by fragmentbyte** [comment]
Automatic generation - it's even better!

This [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/) :(

**Comment by til-schneider** [comment]
The automatic TOC is now available with version 3.
