### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by q2apro** [murfman-de/slim-wiki#7]
Hi, I am trying the software and am new to nodejs.

I installed Node.js, I did the command line (windows), then startet wamp and navigated to the dist folder.
1. The theme CSS file is not in `dist`. The site appears without css.
2. When clicking on "edit" there is an htaccess popup for the login
3. In the readme, there is a config.xml stated: "Create a config.xml (copy and adjust the example)." However, I can only find a PHP file: `config-example.php` There is no config.xml. Maybe you mean `config.php`
4. Creation of user did only work with config.php and then entering the credentials in the popup (see n°2). Would be more convenient to have a user login field. 

It looks to me that there is no revision history.

Just some notes in hope it might help the project.

**Comment by til-schneider** [comment]
You are mixing several question into one issue. Please create separate issues for separate problems in future. This reduces the need of quoting and keeps the issue more readable.

> 1. The theme CSS file is not in `dist`. The site appears without css.
> 2. When clicking on "edit" there is an htaccess popup for the login

Please read the `README.md`. If you still have problems, create a new issue.

> 1. In the readme, there is a config.xml stated: "Create a config.xml (copy and adjust the example)." However, I can only find a PHP file: `config-example.php` There is no config.xml. Maybe you mean `config.php`

Yes, you're right. This is a typo. I meant `config.php`.

> 1. Creation of user did only work with config.php and then entering the credentials in the popup (see n°2). Would be more convenient to have a user login field. 

I don't understand this one. What would you expect exactly and why would it be more convenient?

> It looks to me that there is no revision history.

There is a regular git history. You can find a Web version here: https://github.com/til-schneider/slim-wiki/commits/master
